export enum CharactersTypes {
  CHARACTERS_REQUEST = "CHARACTERS_REQUEST",
  ALL_CHARACTERS_SUCCESS = "ALL_CHARACTERS_SUCCESS",
  SINGLE_CHARACTER_SUCCESS = "SINGLE_CHARACTER_SUCCESS",
  MULTIPLE_CHARACTERS_SUCCESS = "MULTIPLE_CHARACTERS_SUCCESS",
  CHARACTERS_FAIL = "CHARACTERS_FAIL",
}
